services:
  postgres:
    image: "postgres:16.4-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: "postgres:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
    ports:
      - "5433:80"
    depends_on:
      - postgres
  s3service:
    image: quay.io/minio/minio:latest
    volumes:
      - ./storage/:/storage
    command: server --console-address ":9001" /storage
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env.development
  initialize-s3service:
    image: quay.io/minio/mc
    depends_on:
      - s3service
    entrypoint: >
      /bin/sh -c '
      until (/usr/bin/mc config host add s3service http://s3service:9000 "$${MINIO_ROOT_USER}" "$${MINIO_ROOT_PASSWORD}") do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb s3service/"$${S3_BUCKET_NAME}";
      /usr/bin/mc admin user add s3service "$${S3_ACCESS_KEY}" "$${S3_SECRET_KEY}";
      /usr/bin/mc admin policy attach s3service readwrite --user "$${S3_ACCESS_KEY}";
      exit 0;
      '
    env_file: .env.development
