name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Create coverage files
        run: deno test -A --coverage=coverage # create coverage files

      - name: Create coverage report
        run: deno coverage coverage --lcov --output=coverage/lcov.info # create coverage report

      - name: Collect coverage
        uses: codecov/codecov-action@v4 # upload the report on Codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
