name: Deploy

on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --ignore-scripts

      - name: Build step
        run: bun run build

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run migrations
        run: bun run kysely -- migrate:latest

      - name: Run tests
        run: bun run test

      - name: Upload coverage deno
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov-deno.info

      - name: Upload coverage web
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: vasi
          root: ""
          include: .env,api,dist
          entrypoint: ./api/core/server.ts
          import-map: ./api/import-map.production.json
